### ISSUE TITLE
How can I get current selected row from TableView widget?

### ISSUE THREAD

**Issue by jedi2light** [frmdstryr/enamlx#13]
How can I get current selected row from TableView widget?

**Comment by frmdstryr** [comment]
The [selection](https://github.com/frmdstryr/enamlx/blob/master/enamlx/widgets/abstract_item_view.py#L103) list should contain all the selected rows.

Also see [on_selection_changed](https://github.com/frmdstryr/enamlx/blob/master/enamlx/qt/qt_abstract_item_view.py#L351). You can also access the underlying QTableView directly using `self.proxy.widget` if those don't do what you need.

**Comment by jedi2light** [comment]
One more question, how can I use `selection` attribute for next use case:

```
Form:
            attr selection << table.selection
            Form:
                VGroup:
                    Label:
                        text = "Train Number"
                    IntField:
                        pass
                    Label:
                        text = "Train Destination"
                    Field:
                        pass
```

Is it possible to solve the problem by set default `selection` for 0 row in table?

**Comment by frmdstryr** [comment]
Can you provide an example of what you're trying to achieve? In the code you have given the selection is not used.

The default selection is "no selection" ex an empty list. 

If you're trying to display the selected item in a form either use a Conditional to hide the form when no selection is given or use the first item from the items list

```python
attr selected_item << table.selection[0].item if table.selection or table.items[0]
```
where `item` is an attr on the row widget.
