### ISSUE TITLE
Project requirements

### ISSUE THREAD

**Issue by petrushy** [frmdstryr/enamlx#2]
Hi, Looks like an Interesting project!

I have tried to run the examples but get several errors related to qt. What are the project requirements? I'm on (anaconda) python 2.7.10, pyqt 4.10.4, enaml 0.9.8

Regards
/P

for example:
File "C:\Users\phy\Development\Source\enamlx\enamlx\qt\qt_table_widget.py", line 86, in set_resize_mode
    'interactive':QtGui.QHeaderView.ResizeMode.Interactive,
AttributeError: type object 'ResizeMode' has no attribute 'Interactive'

 File "C:\Users\phy\Development\Source\enamlx\enamlx\qt\qt_abstract_item.py", line 129, in init_widget
    self.declaration.column = self.parent().items().index(self)
AttributeError: 'QtTreeWidget' object has no attribute 'items'

**Comment by frmdstryr** [comment]
I've only been using PySide... looks like there are some minor differences. Please pull the latest and try.

**Comment by petrushy** [comment]
Hi, now it starts, great!

Some more bugs I think are related:

For the table widget I get an error clicking the name box:

  File "C:\Users\phy\Development\Source\enamlx\enamlx\qt\qt_abstract_item.py", line 256, in is_checked
    return self.widget.checkState() == Qt.CheckState.Checked
AttributeError: type object 'CheckState' has no attribute 'Checked'

typing a number in the age cell:
 File "C:\Users\phy\Development\Source\enamlx\enamlx\qt\qt_abstract_item.py", line 241, in on_item_selection_changed
    self.declaration.selected = selected
TypeError: The 'selected' member on the 'TableWidgetItem' object must be of type 'bool'. Got object of type 'NoneType' instead.

Tree widget does not start, I get error message:
  File "C:\Users\phy\Development\Source\enamlx\enamlx\qt\qt_abstract_item.py", line 136, in init_widget
    self.declaration.column = self.parent().items().index(self)
AttributeError: 'QtTreeWidget' object has no attribute 'items'

The table view example seems to run fine, great!

**Comment by frmdstryr** [comment]
Pull again...  Checkboxes can't be edited in the TreeWidget and TableView right now for some reason.

**Comment by frmdstryr** [comment]
Stale. Please reopen if needed.
