### ISSUE TITLE
Tag 0.4.2 and 0.4.3

### ISSUE THREAD

**Issue by raboof** [frmdstryr/enamlx#22]
I see 0.4.2 and 0.4.3 are uploaded to pypi.

However I like to build from source, and there doesn't seem to be a github release/tag for these releases. Would it be possible to push those?

Thanks!

**Comment by frmdstryr** [comment]
Just pushed them, let me know if it I did that correctly. The 0.4.2 tag may be off by a commit, I don't remember...

**Comment by raboof** [comment]
Yes that seems to do the trick, thanks!
