### ISSUE TITLE
Not python 3 compatible

### ISSUE THREAD

**Issue by tiagopereira** [frmdstryr/enamlx#7]
Hi,

Thank you for your work, I think it will be a very useful package! Unfortunately it doesn't work under python 3. I managed to get it to work (at least some of the examples) by fixing a few print statements to functions, and using `basestring = (str, bytes)` because basestring is no longer defined in Python 3.

**Comment by frmdstryr** [comment]
Thanks for showing interest :). I don't use Python 3, but free to make a PR.

**Comment by frmdstryr** [comment]
Python 3 support was added in December.
