### ISSUE TITLE
AttributeError: 'QHeaderView' object has no attribute 'setResizeMode'

### ISSUE THREAD

**Issue by bj0** [frmdstryr/enamlx#9]
I am getting this error with PyQT5, at:

    File "...\enamlx\qt\qt_table_view.py", line 87, in set_resize_mode
        self.widget.horizontalHeader().setResizeMode(RESIZE_MODES[mode])

According to this SO post, this is renamed in PyQT5: https://stackoverflow.com/questions/26141161/pyqt4-code-not-working-on-pyqt5-qheaderview

**Comment by frmdstryr** [comment]
Thanks! Looks like this was fixed for the TreeView but not the TableView. 

Added in https://github.com/frmdstryr/enamlx/commit/d86a3e4b89dffeb93adb23cdb9d8fbc20ab68b90
